name: Feature Request
description: Propose a new feature or enhancement for AIMO Standard
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please fill out the information below.

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of AIMO Standard would this feature affect?
      options:
        - Documentation (docs/)
        - JSON Schemas (schemas/)
        - Templates (templates/)
        - Examples (examples/)
        - Validator (validator/)
        - Tooling (tooling/)
        - Coverage Map
        - Taxonomy
        - Other
    validations:
      required: true

  - type: dropdown
    id: change_type
    attributes:
      label: Change Type
      description: Is this a breaking change?
      options:
        - Non-breaking (additive or clarification)
        - Potentially breaking (needs discussion)
        - Breaking (requires major version bump)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or use case...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How would you solve this problem?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
    validations:
      required: false

  - type: checkboxes
    id: i18n
    attributes:
      label: i18n Impact
      description: Does this require translation updates?
      options:
        - label: This feature requires updates to both EN and JA documentation
        - label: This feature is language-neutral (schemas, tooling only)

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might help (examples, references, etc.)
    validations:
      required: false
