#!/usr/bin/env python3
"""
Generate redirect HTML files for legacy URLs.

This script creates static HTML redirect pages in the site/ directory
after mkdocs build. These redirects ensure backward compatibility
for external references (audit firms, client materials, bookmarks).

Usage:
    python tooling/release/build_redirects.py [--site-dir SITE_DIR]

The script reads redirect mappings and generates HTML files with
meta refresh redirects at the legacy URL locations.
"""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SITE_DIR = ROOT / "site"

# Redirect mappings: old_path -> new_path
# Paths are relative to site root (without leading slash)
# Both EN and JA versions are generated automatically
#
# Note: Root-level legacy paths (/standard/versions/, /standard/current/)
# are generated by the GitHub Actions workflow directly on gh-pages branch.
# See .github/workflows/docs_current.yml and release.yml for details.
REDIRECT_MAPS = {
    # /versions/ was moved under /standard/versions/
    "versions/index.html": "standard/versions/",
    # Legacy direct paths without /standard/ prefix
    "current/index.html": "standard/current/",
    "current/01-overview/index.html": "standard/current/01-overview/",
    "current/02-scope/index.html": "standard/current/02-scope/",
    "current/03-taxonomy/index.html": "standard/current/03-taxonomy/",
    "current/04-codes/index.html": "standard/current/04-codes/",
    "current/05-dictionary/index.html": "standard/current/05-dictionary/",
    "current/06-ev-template/index.html": "standard/current/06-ev-template/",
    "current/07-validator/index.html": "standard/current/07-validator/",
    "current/08-changelog/index.html": "standard/current/08-changelog/",
}

REDIRECT_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="0; url={target}">
    <link rel="canonical" href="{target}">
    <title>Redirecting...</title>
</head>
<body>
    <p>This page has moved. If you are not redirected automatically, <a href="{target}">click here</a>.</p>
</body>
</html>
'''


def calculate_relative_target(source_path: str, target_path: str) -> str:
    """
    Calculate relative path from source to target.
    
    Args:
        source_path: e.g., "versions/index.html"
        target_path: e.g., "standard/versions/"
    
    Returns:
        Relative path from source to target
    """
    source_parts = Path(source_path).parent.parts
    target_parts = Path(target_path).parts
    
    # Calculate how many levels up to go
    up_levels = len(source_parts)
    
    # Build relative path
    if up_levels == 0:
        return target_path
    else:
        return "../" * up_levels + target_path


def generate_redirects(site_dir: Path, verbose: bool = True) -> list[tuple[str, str]]:
    """
    Generate redirect HTML files in site directory.
    
    Args:
        site_dir: Path to mkdocs site output directory
        verbose: Print progress messages
    
    Returns:
        List of (created_path, target) tuples
    """
    created = []
    
    # Generate for EN (root)
    for source, target in REDIRECT_MAPS.items():
        source_file = site_dir / source
        
        # Skip if source already exists (don't overwrite real content)
        if source_file.exists():
            if verbose:
                print(f"  Skipping {source} (already exists)")
            continue
        
        # Create parent directories
        source_file.parent.mkdir(parents=True, exist_ok=True)
        
        # Calculate relative target
        relative_target = calculate_relative_target(source, target)
        
        # Write redirect HTML
        source_file.write_text(REDIRECT_TEMPLATE.format(target=relative_target))
        created.append((str(source_file.relative_to(site_dir)), target))
        
        if verbose:
            print(f"  Created {source} -> {target}")
    
    # Generate for JA
    for source, target in REDIRECT_MAPS.items():
        ja_source = f"ja/{source}"
        ja_target = f"ja/{target}"
        source_file = site_dir / ja_source
        
        # Skip if source already exists
        if source_file.exists():
            if verbose:
                print(f"  Skipping {ja_source} (already exists)")
            continue
        
        # Create parent directories
        source_file.parent.mkdir(parents=True, exist_ok=True)
        
        # Calculate relative target (same structure, just under /ja/)
        relative_target = calculate_relative_target(source, target)
        
        # Write redirect HTML
        source_file.write_text(REDIRECT_TEMPLATE.format(target=relative_target))
        created.append((str(source_file.relative_to(site_dir)), ja_target))
        
        if verbose:
            print(f"  Created {ja_source} -> {ja_target}")
    
    return created


def verify_targets(site_dir: Path, verbose: bool = True) -> list[str]:
    """
    Verify that all redirect targets exist.
    
    Returns:
        List of missing targets
    """
    missing = []
    
    for target in REDIRECT_MAPS.values():
        # Check EN target
        target_path = site_dir / target
        if target_path.is_dir():
            target_path = target_path / "index.html"
        
        if not target_path.exists():
            missing.append(target)
            if verbose:
                print(f"  WARNING: Target not found: {target}")
        
        # Check JA target
        ja_target = f"ja/{target}"
        ja_target_path = site_dir / ja_target
        if ja_target_path.is_dir():
            ja_target_path = ja_target_path / "index.html"
        
        if not ja_target_path.exists():
            missing.append(ja_target)
            if verbose:
                print(f"  WARNING: Target not found: {ja_target}")
    
    return missing


def main():
    parser = argparse.ArgumentParser(
        description="Generate redirect HTML files for legacy URLs"
    )
    parser.add_argument(
        "--site-dir",
        type=Path,
        default=DEFAULT_SITE_DIR,
        help=f"Path to site directory (default: {DEFAULT_SITE_DIR})"
    )
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="Only verify targets exist, don't generate redirects"
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress progress output"
    )
    args = parser.parse_args()
    
    verbose = not args.quiet
    
    if not args.site_dir.exists():
        print(f"ERROR: Site directory not found: {args.site_dir}")
        print("Run 'mkdocs build' first.")
        return 1
    
    if verbose:
        print("=" * 60)
        print("AIMO Standard Redirect Generator")
        print("=" * 60)
        print()
    
    # Verify targets exist
    if verbose:
        print("Verifying redirect targets...")
    
    missing = verify_targets(args.site_dir, verbose)
    
    if missing:
        print(f"\nERROR: {len(missing)} redirect target(s) not found!")
        print("Ensure mkdocs build completed successfully.")
        return 1
    
    if verbose:
        print(f"  All {len(REDIRECT_MAPS)} targets verified.\n")
    
    if args.verify_only:
        print("Verification complete.")
        return 0
    
    # Generate redirects
    if verbose:
        print("Generating redirect files...")
    
    created = generate_redirects(args.site_dir, verbose)
    
    if verbose:
        print()
        print("=" * 60)
        print(f"Summary: {len(created)} redirect(s) created")
        print("=" * 60)
    
    return 0


if __name__ == "__main__":
    exit(main())
